### ISSUE TITLE
Modifications to be  made in contact section of ACM-W

### ISSUE THREAD

**Issue by Gandheesh-SA** [aravindvnair99/FACE-Amrita-Bengaluru#139] opened 2020-03-24 17:52 UTC
**Describe the bug**
A unnecessary contact us in the footer section.

**To Reproduce**
1. Go to https://faceaseb.com/ACMW
2. Scroll down to Contact Us section

**Expected behavior**
An unexpected contact us line above the contact number.
Screenshot
![Desktop Screenshot 2020 03 24 - 23 09 31 62_LI](https://user-images.githubusercontent.com/56604198/77459647-0a5e8280-6e26-11ea-98d8-6754bcf7412d.jpg)

**Desktop (please complete the following information):**
Lenovo Legion Laptop
Windows 10 1903
Google Chrome

**Comment by aravindvnair99** [comment] 2020-03-25 08:59
@Gandheesh-SA Can you merge this with #138 as they are of the same context? Will help us track issues easily. You can update the title to "Footer bugs" and mention everything there.

**Comment by aravindvnair99** [comment] 2020-03-25 09:22
Duplicate of #138

**Closed by aravindvnair99** 2020-03-25 09:22 UTC
Labels: ACM-W, EJS, bug, duplicate
